"""fit to MySQL

Revision ID: 201609291235
Revises: None
Create Date: 2016-03-06 19:11:38.238238

"""

# revision identifiers, used by Alembic.
revision = '201609291235'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=16), nullable=True),
    sa.Column('event', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=16), nullable=True),
    sa.Column('scheduled_start_time', sa.String(length=8), nullable=True),
    sa.Column('scheduled_end_time', sa.String(length=8), nullable=True),
    sa.Column('scheduled_end_time', sa.String(length=8), nullable=True),
    sa.Column('scheduled_type', sa.String(length=8), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=16), nullable=True),
    sa.Column('event_id', sa.String(length=16), nullable=True),
    sa.Column('event_datetime', sa.String(length=20), nullable=True),
    sa.Column('event', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('operation', sa.String(length=16), nullable=True),
    sa.Column('operation_type', sa.String(length=16), nullable=True),
    sa.Column('operation_datetime', sa.String(length=20), nullable=True),
    sa.Column('sysinfo_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('host_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('max_cpu', sa.Integer(), nullable=True),
    sa.Column('max_memory', sa.Integer(), nullable=True),
    sa.Column('max_disk', sa.Integer(), nullable=True),
    sa.Column('max_postgres', sa.Integer(), nullable=True),
    sa.Column('max_mysql', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('exception', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sysinfo_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=16), nullable=True),
    sa.Column('sys_datetime', sa.String(length=20), nullable=True),
    sa.Column('cpu', sa.String(length=128), nullable=True),
    sa.Column('memory', sa.String(length=128), nullable=True),
    sa.Column('disk', sa.String(length=128), nullable=True),
    sa.Column('service', sa.Text(), nullable=True),
    sa.Column('database', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_list')
    op.drop_table('event_log')
    op.drop_table('host_list')
    op.drop_table('post_log')
    op.drop_table('sysinfo_log')
    ### end Alembic commands ###
